import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

import styles from '../styles/pages/About.module.scss'

const About: NextPage = () => {

  return (
    <div className={styles.about_container}>
      <Head>
        <title>Pokémon Click N Collect | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball2.png" />
      </Head>
      <h2>About Page</h2>
    </div>
  )
}

export default About