import React from 'react'
import Head from 'next/head'

import styles from '../styles/pages/Contact.module.scss'


const contact = () => {
  return (
    <div className={styles.contact_container}>
      <Head>
        <title>Pokémon Click N Collect | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball2.png" />
      </Head>
        <h2>Contact Page</h2>
    </div>
  )
}

export default contact