import React, { useContext } from 'react'
import Head from 'next/head'
import Link from 'next/link'


import styles from '../styles/pages/Profil.module.scss'

import { GlobalContext } from '../context/GlobalContext'


const User = () => {

  const { userFullInfos } = useContext(GlobalContext)

  const alreadyGotCards = userFullInfos?.cardsList.filter((card) => card.quantity > 0)

  return (
    <div className={styles.profil_container}>
      <Head>
        <title>Pokémon Click N Collect | Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball2.png" />
      </Head>
        <h3>Work in progress ... </h3>
        <p>Pseudo : {userFullInfos?.pseudo}</p>
        <p>PokeCoins : {userFullInfos?.pokeCoin}</p>
        <p>PokeCardex : {alreadyGotCards?.length} / 151</p>
        <p>Mail : {userFullInfos?.mail}</p>
        <p>Admin : {userFullInfos?.isAdmin}</p>
        <Link href="/collection"><button>Collection</button></Link>
    </div>
  )
}

export default User