import React, { useContext } from 'react'
import Head from 'next/head'
import Link from 'next/link'

import { DateTime } from 'luxon'


import styles from '../styles/pages/Profil.module.scss'

import { GlobalContext } from '../context/GlobalContext'


const User = () => {

  const { userFullInfos } = useContext(GlobalContext)

  const alreadyGotCards = userFullInfos?.cardsList.filter((card) => card.quantity > 0)

  const dtDB = userFullInfos?.next_click;

  const dtNow = DateTime.local().toFormat('yyyy-MM-dd HH:mm:ss')

  const checkDate = (dtDB:string,dtNow:string) => {
    if (dtDB < dtNow) {
      return <button>Click pour cartes</button>
    } else {
      return <button disabled>Click pour cartes</button>
    }
  }

  return (
    <div className={styles.profil_container}>
      <Head>
        <title>Pokémon Click N Collect | Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball2.png" />
      </Head>
      {dtDB && checkDate(dtDB, dtNow)}
      <h3>Work in progress ... </h3>
      <p>Pseudo : {userFullInfos?.pseudo}</p>
      <p>PokeCoins : {userFullInfos?.pokeCoin}</p>
      <p>PokeCardex : {alreadyGotCards?.length} / 151</p>
      <p>Mail : {userFullInfos?.mail}</p>
      <p>Admin : {userFullInfos?.isAdmin}</p>
      <p>Next Click : {userFullInfos?.next_click}</p>
        </div>
  )
}

export default User