import React, { useContext, useState, useEffect} from 'react'
import Head from 'next/head'
import Link from 'next/link'
import axios from 'axios'

import styles from '../styles/pages/Profil.module.scss'

import { GlobalContext } from '../context/GlobalContext'

const {DateTime} = require('luxon')

const User = () => {

  
  
  const [ btnIsDisabled, setBtnIsDisabled ] = useState(true)
  
  const { userFullInfos, checkLocalStorage } = useContext(GlobalContext)
  
  const alreadyGotCards = userFullInfos?.cardsList.filter((card) => card.quantity > 0)

  const getRandomCard = () => {
    console.log("j'ai cliqué")
    const newNext_click = DateTime.local().plus({hours: 1}).toISO()
    const localToken = localStorage.getItem('@pkm-cnc')
    axios.get(`/api/cards/getRandomCard`, {
      headers: {
        'Authorization': `Bearer ${localToken}`
      },
      params: {
        next_click: newNext_click
      }
      })
    .then((res) => {
      setBtnIsDisabled(true)
      console.log(res.data);
      checkLocalStorage()
    })
  }

  const getBonusRandomCard = () => {
    console.log("j'ai cliqué")
    const localToken = localStorage.getItem('@pkm-cnc')
    axios.get(`/api/cards/getBonusRandomCard`, {
      headers: {
        'Authorization': `Bearer ${localToken}`
      }
    })
    .then((res) => {
      console.log(res.data);
      checkLocalStorage()
    })
  }


  const decrementCountdown = () => {
    if (userFullInfos?.next_click) {
      const hydrateDT = DateTime.fromISO(userFullInfos?.next_click).toMillis()
      const dtNow = DateTime.local().toMillis()
      if(dtNow < hydrateDT) {
        console.log(hydrateDT - dtNow);
        
      }
    }
  }

  const checkDate = () => {
    if (userFullInfos?.next_click){
      const hydrateDT = DateTime.fromISO(userFullInfos?.next_click).toMillis()
      const dtNow = DateTime.local().toMillis()
      if(dtNow > hydrateDT) {
        setBtnIsDisabled(false)
      } else {
        setBtnIsDisabled(true)
      }
    }
  }

  useEffect(()=> {
    if (userFullInfos?.next_click){
      const hydrateDT = DateTime.fromISO(userFullInfos?.next_click)
      const dtNow = DateTime.local()
      if(dtNow < hydrateDT) {
        const interval = setInterval(() => {
          checkDate()
          console.log("truc");
          
        },1000)
        return () => clearInterval(interval)
      } 
    }
  },[userFullInfos, btnIsDisabled])

  useEffect(()=> {
    checkDate()
  } ,[])


  return (
    <div className={styles.profil_container}>
      <Head>
        <title>Pokémon Click N Collect | Profil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball2.png" />
      </Head>
      {userFullInfos?.bonus_click &&
        userFullInfos.bonus_click > 0 ? <button onClick={getBonusRandomCard}>Click Bonus {userFullInfos.bonus_click}</button> : null
      }
      <button disabled={btnIsDisabled} onClick={getRandomCard}>Get Random Card</button>
      <h3>Work in progress ... </h3>
      <p>Pseudo : {userFullInfos?.pseudo}</p>
      <p>PokeCoins : {userFullInfos?.pokeCoin}</p>
      <p>PokeCardex : {alreadyGotCards?.length} / 151</p>
      <p>Mail : {userFullInfos?.mail}</p>
      <p>Admin : {userFullInfos?.isAdmin}</p>
      <p>Next Click : {userFullInfos?.next_click}</p>
      </div>
  )
}

export default User