//Base React + Componsant Image de Next.js + Axios
import React, { useEffect, useState } from 'react'
import Head from 'next/head'

import Image from 'next/image'
import axios from 'axios';
// Style
import styles from '../styles/pages/Shop.module.scss'
import Card from '../comps/Card';
import BuyBtn from '../comps/BuyBtn';

//type
interface IPokemon {
  _id: string;
  gen: number;
  dex_number: number;
  name: string;
  type: string[];
  description: string;
  picURL: string;
  price: number;
  height: number;
  weight: number;
  rarity: string;
}

const Shop = () => {
  //State
  const [cards, setCards] = useState<IPokemon[]>([])
  const [loading, setLoading] = useState(true)
  //Fetch data before render
  useEffect(() => {
    axios.get('/api/cards/getAllCardsFromDB')
      .then(res => {
        setCards(res.data.data)
        setLoading(false)
      })
  },[])

  return (
    <div className={styles.shop_container}>
      <Head>
        <title>Pokémon Click N Collect | Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball2.png" />
      </Head>
        <h2>Boutique</h2>
        <div className={styles.cards_container}>
            {!loading ? cards.map((card, index) => {
              return (
                <div className={styles.sub_card_container} key={index}>
                  <Card  card={card} />
                  <BuyBtn card={card} />
                </div>
              )
            }) : <p>Chargement des cartes ...</p>}
        </div>
    </div>
  )
}
export default Shop
