//Base React + Componsant Image de Next.js + Axios
import React, { useEffect, useState } from 'react'
import Head from 'next/head'

import Image from 'next/image'
import axios from 'axios';
// Style
import styles from '../styles/pages/Shop.module.scss'
import Card from '../comps/Card';
import BuyCardModal from '../comps/BuyCardModal';

//type
interface IPokemon {
  _id: string;
  gen: number;
  dex_number: number;
  name: string;
  type: string[];
  description: string;
  picURL: string;
  price: number;
  height: number;
  weight: number;
  rarity: string;
}

const Shop = () => {
  //State
  const [cards, setCards] = useState<IPokemon[]>([])
  const [loading, setLoading] = useState(true)
  const [ showBuyCardModal, setShowBuyCardModal ] = useState(false)
  const [ modalInfos, setModalInfos ] = useState({cardID:"", cardName:"",userID:"", userCoin:""})
  //Fetch data before render
  useEffect(() => {
    axios.get('/api/cards/getAllCardsFromDB')
      .then(res => {
        setCards(res.data.data)
        setLoading(false)
      })
  },[])

  return (
    <div className={styles.shop_container}>
      <Head>
        <title>Pokémon Click N Collect | Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball2.png" />
      </Head>
        <h2>Boutique</h2>
        <div className={styles.cards_container}>
          {!loading ? cards.map((card) => {
            return (
              <Card key={card._id} card={card} setShowBuyCardModal={setShowBuyCardModal} setModalInfos={setModalInfos}/>
            )
          }) : <p>Chargement des cartes ...</p>}
        </div>
        {showBuyCardModal && <BuyCardModal setShowBuyCardModal={setShowBuyCardModal} modalInfos={modalInfos}/>}
    </div>
  )
}
export default Shop
